### PR TITLE
Add Bank Storage + EMI support

### PR DESCRIPTION
**Pull request by unilock**
This PR adds support for [Bank Storage](https://modrinth.com/mod/bank-storage)'s "banks" as item suppliers for construction wands, as well as [EMI](https://modrinth.com/mod/emi) as an alternative to REI for viewing item info.

### CODE REVIEW

**Comment by JongWasTaken** [comment]
Hey there!  
Thank you for your work! More mod compatibility is always welcome, especially since Fabric doesn't really have one universal API for this kind of stuff.

**Comment by unilock** [comment]
After further testing, it looks like this PR does not function properly when the client is connected to a dedicated server, wrt the Bank Storage integration :s 

I think it's because CachedBankStorage is used client-side, while something else is used server-side? The mod doesn't have an API, unfortunately, so I'll have to take a closer look at it.

**Comment by JongWasTaken** [comment]
I think I managed to fix it in [890fe54](https://github.com/JongWasTaken/ConstructionWand-Fabric/commit/890fe54a4f95159327718e448d8ad7488ca91d0f). It is a bit awkward because using `Util.getBankItemStorage(inventoryStack, player.getWorld());` seems to crash the game when used in single player, so it will use CachedBankStorage instead.  
I don't really know this mod though, so please let me know if I missed something.

**Comment by unilock** [comment]
I managed to fix it on both singleplayer and multiplayer worlds with https://github.com/unilock/ConstructionWand-Fabric/commit/764596d5234a68f7a4c847b92e52532b859077e8. This also fixes the item count in banks not updating until observed in multiplayer.

If you want to revert that last commit, I can make another pull request, or you can just merge the changes manually :)

**Comment by JongWasTaken** [comment]
Great! Please create another PR and I will gladly merge it!

**Pull request merged**
